lista_tematicas =[
    {
        "tematica": "Cantantes argentinas",
        "Pregunta": "Cantantes argentinas que tienen menos de 40 años.",
        "Respuesta_1": "Lali",
        "Cantidad_R1": 43,
        "Respuesta_2": "Tiny",
        "Cantidad_R2": 22,
        "Respuesta_3": "Nicki Nicole",
        "Cantidad_R3": 20,
        "Respuesta_4": "Maria Becerra",
        "Cantidad_R4": 14,
        "Respuesta_5": "Mercedes Sosa",
        "Cantidad_R5": 1,
    },
    {
        "tematica": "Actores de hollywood",
        "Pregunta": "¿Quienes Ganaron el Oscar en 2022?",
        "Respuesta_1": "Messi",
        "Cantidad_R1": 54,
        "Respuesta_2": "Francella",
        "Cantidad_R2": 6,
        "Respuesta_3": "Di Caprio",
        "Cantidad_R3": 20,
        "Respuesta_4": "Brad Pitt",
        "Cantidad_R4": 14,
        "Respuesta_5": "Wil Smith",
        "Cantidad_R5": 6,
    },
    {
        "tematica": "Cocina internacional",
        "Pregunta": "¿Plato típico de la cocina italiana?",
        "Respuesta_1": "Pizza",
        "Cantidad_R1": 30,
        "Respuesta_2": "Pasta",
        "Cantidad_R2": 25,
        "Respuesta_3": "Lasagna",
        "Cantidad_R3": 20,
        "Respuesta_4": "Tiramisú",
        "Cantidad_R4": 15,
        "Respuesta_5": "Risotto",
        "Cantidad_R5": 10,
    },
    {
        "tematica": "Animales salvajes",
        "Pregunta": "¿Nombre de un felino grande?",
        "Respuesta_1": "León",
        "Cantidad_R1": 30,
        "Respuesta_2": "Tigre",
        "Cantidad_R2": 25,
        "Respuesta_3": "Leopardo",
        "Cantidad_R3": 20,
        "Respuesta_4": "Pantera",
        "Cantidad_R4": 15,
        "Respuesta_5": "Guepardo",
        "Cantidad_R5": 10,
    },
    {
        "tematica": "Películas clásicas",
        "Pregunta": "¿Nombre de una película de Alfred Hitchcock?",
        "Respuesta_1": "Psicosis",
        "Cantidad_R1": 30,
        "Respuesta_2": "Los pájaros",
        "Cantidad_R2": 25,
        "Respuesta_3": "Vértigo",
        "Cantidad_R3": 20,
        "Respuesta_4": "La ventana indiscreta",
        "Cantidad_R4": 15,
        "Respuesta_5": "Crimen perfecto",
        "Cantidad_R5": 10,
    },
    {
        "tematica": "Cantantes argentinas",
        "Pregunta": "¿Cuál es tu cantante argentina favorita?",
        "Respuesta_1": "Lali",
        "Cantidad_R1": 25,
        "Respuesta_2": "Tini",
        "Cantidad_R2": 20,
        "Respuesta_3": "Jimena Barón",
        "Cantidad_R3": 15,
        "Respuesta_4": "María Becerra",
        "Cantidad_R4": 25,
        "Respuesta_5": "Sofía Reyes",
        "Cantidad_R5": 15,
    },
    {
        "tematica": "Actores de Hollywood",
        "Pregunta": "¿Quién es tu actor de Hollywood favorito?",
        "Respuesta_1": "Brad Pitt",
        "Cantidad_R1": 20,
        "Respuesta_2": "Leonardo DiCaprio",
        "Cantidad_R2": 30,
        "Respuesta_3": "Tom Hanks",
        "Cantidad_R3": 10,
        "Respuesta_4": "Meryl Streep",
        "Cantidad_R4": 15,
        "Respuesta_5": "Denzel Washington",
        "Cantidad_R5": 25,
    },
    {
        "tematica": "Cocina internacional",
        "Pregunta": "¿Plato típico de la cocina francesa?",
        "Respuesta_1": "Croissant",
        "Cantidad_R1": 15,
        "Respuesta_2": "Cassoulet",
        "Cantidad_R2": 25,
        "Respuesta_3": "Escargot",
        "Cantidad_R3": 10,
        "Respuesta_4": "Ratatouille",
        "Cantidad_R4": 20,
        "Respuesta_5": "Coq au Vin",
        "Cantidad_R5": 30,
    },
    {
        "tematica": "Animales salvajes",
        "Pregunta": "¿Nombre de un animal en peligro de extinción?",
        "Respuesta_1": "Tigre de Bengala",
        "Cantidad_R1": 15,
        "Respuesta_2": "Rinoceronte negro",
        "Cantidad_R2": 25,
        "Respuesta_3": "Oso polar",
        "Cantidad_R3": 20,
        "Respuesta_4": "Panda gigante",
        "Cantidad_R4": 10,
        "Respuesta_5": "Lince ibérico",
        "Cantidad_R5": 30,
    },
    {
        "tematica": "Películas clásicas",
        "Pregunta": "¿Cuál es la mejor película en blanco y negro?",
        "Respuesta_1": "Casablanca",
        "Cantidad_R1": 25,
        "Respuesta_2": "Ciudadano Kane",
        "Cantidad_R2": 20,
        "Respuesta_3": "Lo que el viento se llevó",
        "Cantidad_R3": 15,
        "Respuesta_4": "El Padrino",
        "Cantidad_R4": 25,
        "Respuesta_5": "El séptimo sello",
        "Cantidad_R5": 15,
    },
    {
        "tematica": "Cantantes argentinas",
        "Pregunta": "¿Cuál es tu canción favorita de una cantante argentina?",
        "Respuesta_1": "Sin Pijama",
        "Cantidad_R1": 10,
        "Respuesta_2": "Ella Dice",
        "Cantidad_R2": 20,
        "Respuesta_3": "Me Gusta",
        "Cantidad_R3": 30,
        "Respuesta_4": "Fresa",
        "Cantidad_R4": 25,
        "Respuesta_5": "Ricochet",
        "Cantidad_R5": 15,
    },
    {
        "tematica": "Actores de Hollywood",
        "Pregunta": "¿Cuál es tu película favorita de Leonardo DiCaprio?",
        "Respuesta_1": "Titanic",
        "Cantidad_R1": 30,
        "Respuesta_2": "El Renacido",
        "Cantidad_R2": 20,
        "Respuesta_3": "Origen",
        "Cantidad_R3": 15,
        "Respuesta_4": "Atrápame si puedes",
        "Cantidad_R4": 25,
        "Respuesta_5": "El Gran Gatsby",
        "Cantidad_R5": 10,
    },
    {
        "tematica": "Cocina internacional",
        "Pregunta": "¿Cuál es el plato nacional de México?",
        "Respuesta_1": "Tacos",
        "Cantidad_R1": 25,
        "Respuesta_2": "Enchiladas",
        "Cantidad_R2": 15,
        "Respuesta_3": "Tamales",
        "Cantidad_R3": 20,
        "Respuesta_4": "Chiles en nogada",
        "Cantidad_R4": 10,
        "Respuesta_5": "Pozole",
        "Cantidad_R5": 30,
    },
    {
        "tematica": "Animales salvajes",
        "Pregunta": "¿Cuál es el animal más rápido del mundo?",
        "Respuesta_1": "Guepardo",
        "Cantidad_R1": 30,
        "Respuesta_2": "Leopardo",
        "Cantidad_R2": 10,
        "Respuesta_3": "Águila",
        "Cantidad_R3": 25,
        "Respuesta_4": "Falcon",
        "Cantidad_R4": 15,
        "Respuesta_5": "Lobo",
        "Cantidad_R5": 20,
    },
    {
        "tematica": "Películas clásicas",
        "Pregunta": "¿Cuál es la película más influyente de todos los tiempos?",
        "Respuesta_1": "El Padrino",
        "Cantidad_R1": 25,
        "Respuesta_2": "Lo que el viento se llevó",
        "Cantidad_R2": 20,
        "Respuesta_3": "Casablanca",
        "Cantidad_R3": 15,
        "Respuesta_4": "2001: Odisea del espacio",
        "Cantidad_R4": 10,
        "Respuesta_5": "El Ciudadano Kane",
        "Cantidad_R5": 30,
    },
    {
        "tematica": "Cantantes argentinas",
        "Pregunta": "¿Cuál es la mejor canción de Lali?",
        "Respuesta_1": "Sin Pijama",
        "Cantidad_R1": 20,
        "Respuesta_2": "Ella Dice",
        "Cantidad_R2": 25,
        "Respuesta_3": "Soy",
        "Cantidad_R3": 10,
        "Respuesta_4": "Besarte Mucho",
        "Cantidad_R4": 15,
        "Respuesta_5": "Somos Amantes",
        "Cantidad_R5": 30,
    },
    {
        "tematica": "Actores de Hollywood",
        "Pregunta": "¿Cuál es la película más taquillera de Brad Pitt?",
        "Respuesta_1": "Troya",
        "Cantidad_R1": 15,
        "Respuesta_2": "El Club de la Lucha",
        "Cantidad_R2": 25,
        "Respuesta_3": "El curioso caso de Benjamin Button",
        "Cantidad_R3": 20,
        "Respuesta_4": "El efecto mariposa",
        "Cantidad_R4": 5,
        "Respuesta_5": "Malditos Bastardos",
        "Cantidad_R5": 35,
    },
    {
        "tematica": "Cocina internacional",
        "Pregunta": "¿Cuál es el plato típico de la gastronomía italiana?",
        "Respuesta_1": "Pizza",
        "Cantidad_R1": 30,
        "Respuesta_2": "Pasta",
        "Cantidad_R2": 20,
        "Respuesta_3": "Lasagna",
        "Cantidad_R3": 15,
        "Respuesta_4": "Risotto",
        "Cantidad_R4": 10,
        "Respuesta_5": "Tiramisú",
        "Cantidad_R5": 25,
    },
    {
        "tematica": "Animales salvajes",
        "Pregunta": "¿Cuál es el animal más grande del planeta?",
        "Respuesta_1": "Elefante africano",
        "Cantidad_R1": 35,
        "Respuesta_2": "Ballena azul",
        "Cantidad_R2": 30,
        "Respuesta_3": "Tiburón blanco",
        "Cantidad_R3": 5,
        "Respuesta_4": "Hipopótamo",
        "Cantidad_R4": 10,
        "Respuesta_5": "Rinoceronte",
        "Cantidad_R5": 20,
    },
    {
        "tematica": "Películas clásicas",
        "Pregunta": "¿Cuál es la película más antigua que aún se proyecta en cines?",
        "Respuesta_1": "El nacimiento de una nación (1915)",
        "Cantidad_R1": 15,
        "Respuesta_2": "Lo que el viento se llevó (1939)",
        "Cantidad_R2": 30,
        "Respuesta_3": "Casablanca (1942)",
        "Cantidad_R3": 25,
        "Respuesta_4": "Lo que hacemos en las sombras (2014)",
        "Cantidad_R4": 5,
        "Respuesta_5": "La La Land (2016)",
        "Cantidad_R5": 25,
    },
    {
        "tematica": "Cantantes argentinas",
        "Pregunta": "¿Cuál es la canción más famosa de Nicki Nicole?",
        "Respuesta_1": "Colocao",
        "Cantidad_R1": 35,
        "Respuesta_2": "Wapo Traketero",
        "Cantidad_R2": 20,
        "Respuesta_3": "Mamichula",
        "Cantidad_R3": 10,
        "Respuesta_4": "Ella no es tuya (remix)",
        "Cantidad_R4": 15,
        "Respuesta_5": "Colocao (remix)",
        "Cantidad_R5": 20,
    },
    {
        "tematica": "Actores de Hollywood",
        "Pregunta": "¿Cuál es la película más taquillera de Tom Hanks?",
        "Respuesta_1": "Forrest Gump",
        "Cantidad_R1": 40,
        "Respuesta_2": "Náufrago",
        "Cantidad_R2": 15,
        "Respuesta_3": "El código Da Vinci",
        "Cantidad_R3": 10,
        "Respuesta_4": "Toy Story",
        "Cantidad_R4": 20,
        "Respuesta_5": "Salvar al soldado Ryan",
        "Cantidad_R5": 15,
    },
    {
        "tematica": "Cocina internacional",
        "Pregunta": "¿Cuál es el plato más picante de la gastronomía tailandesa?",
        "Respuesta_1": "Som tam",
        "Cantidad_R1": 25,
        "Respuesta_2": "Pad Thai",
        "Cantidad_R2": 20,
        "Respuesta_3": "Tom Yum Goong",
        "Cantidad_R3": 30,
        "Respuesta_4": "Khao Pad",
        "Cantidad_R4": 10,
        "Respuesta_5": "Massaman Curry",
        "Cantidad_R5": 15,
    },
    {
        "tematica": "Animales salvajes",
        "Pregunta": "¿Cuál es el felino más rápido del mundo?",
        "Respuesta_1": "Tigre",
        "Cantidad_R1": 10,
        "Respuesta_2": "Guepardo",
        "Cantidad_R2": 55,
        "Respuesta_3": "León",
        "Cantidad_R3": 5,
        "Respuesta_4": "Pantera",
        "Cantidad_R4": 15,
        "Respuesta_5": "Leopardo",
        "Cantidad_R5": 15,
    },
    {
        "tematica": "Películas clásicas",
        "Pregunta": "¿Quién dirigió la película 'El Ciudadano Kane'?",
        "Respuesta_1": "Alfred Hitchcock",
        "Cantidad_R1": 5,
        "Respuesta_2": "Quentin Tarantino",
        "Cantidad_R2": 15,
        "Respuesta_3": "Steven Spielberg",
        "Cantidad_R3": 10,
        "Respuesta_4": "Orson Welles",
        "Cantidad_R4": 50,
        "Respuesta_5": "Martin Scorsese",
        "Cantidad_R5": 20,
    },
]

